GavResorts.Web/Models/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GavResorts.Web.Models;

public class ContactViewModel
{
    public int Id { get; set; }
    [Required]
    public string? Name { get; set; }
    [Required]
    public string? Note { get; set; }
    [Required]
    [Display(Name = "Phone Number")]
    public string? Telephone { get; set; }
    [Required]
    public string? Email { get; set; }
}

GavResorts.Web/Models/ErrorViewModel.cs
namespace GavResorts.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GavResorts.Web/Controllers/ContactsController.cs
using GavResorts.Web.Models;
using GavResorts.Web.Roles;
using GavResorts.Web.Services.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GavResorts.Web.Controllers
{
    public class ContactsController : Controller
    {
        private readonly IContactService _contactService;

        public ContactsController(IContactService contactService)
        {
            _contactService = contactService;
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult<IEnumerable<ContactViewModel>>> Index()
        {
            var result = await _contactService.GetAllContacts(await GetAccessToken());

            if (result is null)
                return View("Error");

            return View(result);
        }

        [HttpGet]
        public IActionResult CreateContact()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateContact(ContactViewModel model)
        {
            if(ModelState.IsValid)
            {
                var result = await _contactService.CreateContact(model, await GetAccessToken());

                if (result != null)
                    return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateContact(int id)
        {
            var result = await _contactService.FindContactById(id, await GetAccessToken());

            if(result == null) return View("Error");

            return View(result);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> UpdateContact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _contactService.UpdateContact(model, await GetAccessToken());

                if (result != null)
                    return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> DeleteContact(int id)
        {
            var result = await _contactService.FindContactById(id, await GetAccessToken());

            if (result == null) return View("Error");

            return View(result);
        }

        [HttpPost(), ActionName("DeleteContact")]
        [Authorize(Roles = Role.Admin)]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _contactService.DeleteContactById(id, await GetAccessToken());

            if (!result)
                return View("Error");
            

            return RedirectToAction("Index");
        }

        private async Task<string?> GetAccessToken()
        {
            return await HttpContext.GetTokenAsync("access_token");
        }
    }
}

GavResorts.Web/Controllers/HomeController.cs
using GavResorts.Web.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GavResorts.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [Authorize]
        public async Task<IActionResult> Login()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Logout()
        {
            return SignOut("Cookies", "oidc");
        }
    }
}

GavResorts.Web/Views/Contacts/CreateContact.cshtml
@model GavResorts.Web.Models.ContactViewModel

<h2>Create a new Contact</h2>

<form asp-action="CreateContact">

    <div class="form-horizontal">
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Telephone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Note" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="Note" style="resize: none" rows="5" class="form-control">
                    It was a dark and stormy night...
                </textarea>
            </div>
        </div>

        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>

    </div>
</form>

GavResorts.Web/Views/Contacts/DeleteContact.cshtml
@model GavResorts.Web.Models.ContactViewModel

<h3>Delete Contact</h3>

<h4>Are you sure you want to delete this?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
    </dl>

    <form asp-action="DeleteContact">
        <input type="hidden" asp-for="Id" />
        <div class="form-group" style="padding-top: 10px">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-info">Back to List</a>
        </div>
    </form>
</div>

GavResorts.Web/Views/Contacts/Index.cshtml
@model IEnumerable<GavResorts.Web.Models.ContactViewModel>

<h2>Contact</h2>
<hr />

<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull left">
                <a asp-action="CreateContact" class="btn btn-primary">
                    <span title="Create New" class="fas fa-plus"></span> New Contact
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Telephone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Note)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelitem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelitem => item.Telephone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelitem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelitem => item.Note)
                    </td>
                    <td>
                        <a asp-action="UpdateContact" asp-route-id="@item.Id" title="Editar" class="btn btn-warning">
                            <span class="fa fa-edit"></span>
                        </a>
                        <a asp-action="DeleteContact" asp-route-id="@item.Id" title="Excluir" class="btn btn-danger">
                            <span class="fa fa-trash-alt"></span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

GavResorts.Web/Views/Contacts/UpdateContact.cshtml
@model GavResorts.Web.Models.ContactViewModel

<h2>Update Contact</h2>

<form asp-action="UpdateContact">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Telephone" class="control-label"></label>
        <textarea asp-for="Telephone" class="form-control"></textarea>
        <span asp-validation-for="Telephone" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <textarea asp-for="Email" class="form-control"></textarea>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Note" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <textarea asp-for="Note" style="resize: none" rows="5" class="form-control">
                Add description
            </textarea>
        </div>
    </div>

    <div class="form-group" style="padding-top: 10px">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-info">Back to List</a>
    </div>
</form>

GavResorts.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3 class="display-4">List of Contacts</h3>
    <img src="/images/Gav_Resorts_Logo.png" class="img-fluid" asp-append-version="true" />
    <h5 class="display-8">Projeto ASP NET CORE API WEB usando o conceito MSC – Model Service Controller.</h5>
    <h5 class="display-8">Cadastro básico de Contatos com Autenticação usando Jwt e Bearer.</h5>
</div>

GavResorts.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GavResorts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GavResorts.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GavResorts</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                    </ul>
                    <ul>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GavResorts
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>